# Generated by Django 3.1.2 on 2020-11-17 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Carecacadb', '0003_auto_20201117_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards_in_group',
            name='Cards_group_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Carecacadb.cards_group'),
        ),
    ]
