# Generated by Django 3.0.8 on 2020-07-18 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesion',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
